namespace Minerals.AutoCommands.Interfaces
{
    [Generator]
    public class ICommandPipelineGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("ICommandPipeline.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            // <auto-generated />

            namespace Minerals.AutoCommands
            {
                public interface ICommandPipeline
                {
                    global::Minerals.AutoCommands.ICommand ParseCommandArgument(string argument);
                }
            }
            """;
            return SourceText.From(source, Encoding.UTF8);
        }
    }
}