namespace Minerals.AutoCommands.Interfaces
{
    [Generator]
    public class ICommandGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("ICommand.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            namespace Minerals.AutoCommands
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public interface ICommand
                {
                    void Evaluate(global::Minerals.AutoCommands.ICommandPipeline pipeline, string[] arguments, int index);
                    void ShowHelp();
                    bool Execute();
                }
            }
            """;
            var builder = new CodeBuilder();
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }
    }
}