namespace Minerals.AutoCommands.Interfaces
{
    [Generator]
    public class ICommandPipelineGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("ICommandPipeline.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            namespace Minerals.AutoCommands
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public interface ICommandPipeline
                {
                    global::Minerals.AutoCommands.ICommand ParseCommandArgument(string argument);
                }
            }
            """;
            var builder = new CodeBuilder();
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }
    }
}