namespace Minerals.AutoCommands.Attributes
{
    [Generator]
    public class CommandPipelineAttributeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("CommandPipelineAttribute.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            // <auto-generated />

            namespace Minerals.AutoCommands
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class CommandPipelineAttribute : global::System.Attribute
                {
                }
            }
            """;
            return SourceText.From(source, Encoding.UTF8);
        }
    }
}