//HintName: CommandPipelineAttribute.g.cs
// <auto-generated />

namespace Minerals.AutoCommands
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class CommandPipelineAttribute : global::System.Attribute
    {
    }
}