//HintName: CommandAttribute.g.cs
// <auto-generated />

#pragma warning disable CS9113
namespace Minerals.AutoCommands
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class CommandAttribute : global::System.Attribute
    {
        public CommandAttribute(params string[] aliases)
        {
        }
    }
}
#pragma warning restore CS9113