//HintName: CommandParser.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoCommands.Generators
// Version: {Removed}
// </auto-generated>
namespace Minerals.AutoCommands
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CommandParser
    {
        public static global::Minerals.AutoCommands.Interfaces.ICommand Parse(string arg, global::System.StringComparison comparison)
        {
            if (arg.Equals("test1", comparison)) return (global::Minerals.AutoCommands.Interfaces.ICommand)new Minerals.Examples.TestCommand1();
            else return null;
        }
    }
}