//HintName: CommandParser.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoCommands.Generators
// Version: {Removed}
// </auto-generated>
namespace Minerals.AutoCommands
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class CommandParser : global::Minerals.AutoCommands.Interfaces.ICommandParser
    {
        private readonly string[] _aliases = new string[] { };

        public global::Minerals.AutoCommands.Interfaces.ICommandStatement Parse(string arg, global::System.StringComparison comparison)
        {
            return null;
        }

        public bool IsAlias(string text, global::System.StringComparison comparison)
        {
            foreach (var item in _aliases)
            {
                if (text.Equals(item, comparison))
                {
                    return true;
                }
            }
            return false;
        }
    }
}