//HintName: ICommand.g.cs
// <auto-generated />

namespace Minerals.AutoCommands
{
    public interface ICommand
    {
        void Evaluate(global::Minerals.AutoCommands.ICommandPipeline pipeline, string[] arguments, int index);
        void ShowHelp();
        bool Execute();
    }
}