//HintName: ICommandPipeline.g.cs
// <auto-generated />

namespace Minerals.AutoCommands
{
    public interface ICommandPipeline
    {
        global::Minerals.AutoCommands.ICommand ParseCommandArgument(string argument);
    }
}