//HintName: InvalidCommand.g.cs
// <auto-generated />

namespace Minerals.AutoCommands
{
    public sealed class InvalidCommand : global::Minerals.AutoCommands.ICommand
    {
        public void Evaluate(global::Minerals.AutoCommands.ICommandPipeline pipeline, string[] arguments, int index)
        {
        }

        public void ShowHelp()
        {
        }

        public bool Execute()
        {
            return false;
        }
    }
}