namespace Minerals.AutoCommands.Attributes
{
    [Generator]
    public class InvalidCommandGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("InvalidCommand.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            namespace Minerals.AutoCommands
            {
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public sealed class InvalidCommand : global::Minerals.AutoCommands.ICommand
                {
                    public void Evaluate(global::Minerals.AutoCommands.ICommandPipeline pipeline, string[] arguments, int index)
                    {
                    }

                    public void ShowHelp()
                    {
                    }

                    public bool Execute()
                    {
                        return false;
                    }
                }
            }
            """;
            var builder = new CodeBuilder();
            builder.AddAutoGeneratedHeader(System.Reflection.Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }
    }
}