namespace Minerals.AutoCommands.Attributes
{
    [Generator]
    public class InvalidCommandGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                context.AddSource("InvalidCommand.g.cs", GenerateAttribute());
            });
        }

        public static SourceText GenerateAttribute()
        {
            const string source = """
            // <auto-generated />

            namespace Minerals.AutoCommands
            {
                public sealed class InvalidCommand : global::Minerals.AutoCommands.ICommand
                {
                    public void Evaluate(global::Minerals.AutoCommands.ICommandPipeline pipeline, string[] arguments, int index)
                    {
                    }

                    public void ShowHelp()
                    {
                    }

                    public bool Execute()
                    {
                        return false;
                    }
                }
            }
            """;
            return SourceText.From(source, Encoding.UTF8);
        }
    }
}